[tool.poetry]
name = "uc3m-rag-chatbot"
version = "1.0.0"
description = "Chatbot RAG usando LangChain, ChromaDB y UC3M LLM"
authors = ["Tu Nombre"]
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

fastapi = "*"
uvicorn = "*"

python-dotenv = "*"
requests = "*"

chromadb = "*"

langchain = "*"
langchain-community = "*"
langchain-core = "*"
langchain-ollama = "*"
langchain-text-splitters = "*"
langgraph = "*"

sentence-transformers = "*"

pydantic = "*"
langchain-huggingface = "^1.1.0"
langchain-chroma = "^1.0.0"
streamlit = "^1.52.1"
unstructured = "^0.18.21"

# Translation dependencies
transformers = "^4.30.0"
torch = "^2.0.0"
sentencepiece = "*"
sacremoses = "*"
